# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nemethnikol <nemethnikol@student.42.fr>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/26 16:23:59 by nemethnikol       #+#    #+#              #
#    Updated: 2022/07/26 16:26:38 by nemethnikol      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = philo

CC = 	gcc

CFLAGS = -Wall -Wextra -Werror -g -fsanitize=address

OBJS = $(SRC:.c=.o)

RM  = rm -fr

SRC = *.c